# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/replicatedcom/ship
    steps:
      - checkout
      - run: make test

  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/replicatedcom/ship
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull debian:stretch-slim # make sure it's fresh
      - run: docker login -u="$DOCKERHUB_DOCKER_USER" -p="$DOCKERHUB_DOCKER_PASS"
      - deploy:
          command: curl -sL https://git.io/goreleaser | bash
  deploy_unstable:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/replicatedcom/ship
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull debian:stretch-slim # make sure it's fresh
      - deploy:
          command: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --config .goreleaser.unstable.yml
      - run: docker login -u="$DOCKERHUB_DOCKER_USER" -p="$DOCKERHUB_DOCKER_PASS"
      - deploy:
          command: docker push replicated/ship:unstable

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
      - deploy_unstable:
          requires:
            - test
          filters:
            branches:
              only: /master/

