apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: grafana
    chart: grafana-1.19.0
    heritage: Tiller
    release: grafana
  name: grafana-clusterrole
rules: []
