apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
    chart: grafana-1.19.0
    heritage: Tiller
    release: grafana
  name: grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 111Gi
  storageClassName: default
