apiVersion: v1
data:
  admin-password: c3Ryb25ncGFzc3dvcmQ=
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app: grafana
    chart: grafana-1.19.0
    heritage: Tiller
    release: grafana
  name: grafana
type: Opaque
