##---
# Source: stable-mysql/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: stable-mysql
  labels:
    app: stable-mysql
    chart: stable-mysql-0.1.0
    release: stable-mysql
    heritage: Tiller
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stable-mysql
      release: stable-mysql
  template:
    metadata:
      labels:
        app: stable-mysql
        release: stable-mysql
    spec:
      containers:
        - name: stable-mysql
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            
