##---
# Source: stable-mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stable-mysql
  labels:
    app: stable-mysql
    chart: stable-mysql-0.1.0
    release: stable-mysql
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: stable-mysql
    release: stable-mysql
