##---
# Source: bitcoind/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  labels:
    app: bitcoind
    chart: bitcoind-0.1.3
    release: bitcoind
    heritage: Tiller
spec:
  ports:
    - name: rpc
      port: 8332
      targetPort: rpc
    - name: p2p
      port: 8333
      targetPort: p2p
    - name: testnet
      port: 18332
    - name: testnet-p2p
      port: 18333
  selector:
    app: bitcoind
    release: bitcoind
